#
############################################
#The amount of time the player needs to sleep to recover all their energy
#-------------------------------------------
#Default: 6000
#-------------------------------------------
#Range: -2147483648 ~ 2147483647
"Integer: Ideal Amount Of Sleep" = 6000

